## Advanced Simulation with Different Parameters ##

### Necessity of RHIPE ###

The goal of statistics is to utilize data to make inferences about a scientific question of interest. To make a problem tractable, assumptions are made and in most scientific cases, appropriate parametric assumptions apply. This can reduce the scope of the problem to a handful of summary statistics gleaned from the data. However, this is not the case of every model. Some models require access to all of the data values for the most accurate conclusions.

For problems in Big Data, this is where R Hadoop Integrated Programming Environment (RHIPE) is absolutely critical. Although placing all the data in a single location to be utilized as necessary is not possible, the Hadoop platform still allows us access to all of the data broken up into subsets across multiple nodes. In this format, analysis on each subset of the data to be combined is still better than not being able to utilize all of the data.

### Simulation Example: AR(2) ###

An example of such a case is estimating the parameter(s) to an Auto Regressive Integrated Moving Average (ARIMA) Model to Time Series Data. For the sake of simplicity, but still abiding by the section title of different parameters, I will use RHIPE to estimate an AR(2) (2 AR parameter terms) Model through simulation.

The RHIPE code needed to run this simulation is not all that much more extensive than the R code necessary to run this simulation. The reason for RHIPE is one of computational storage limitations and speed improvements through parallelization.

```{r eval=FALSE, tidy=FALSE}
N.exp <- 20
N <- 2^N.exp
m.exp <- 10
m <- 2^m.exp
w.vec <- 2*pi*0:(m - 1)/m
rho.true <- c(2/3, -1/3)
rho.init <- c(0, 0)
ginv <- function(lambda, rho1, rho2) 1 + rho1^2 + rho2^2 - 2*rho1*(1 - rho2)*cos(lambda) - 2*rho2*cos(2*lambda))
map <- expression({
  for(i in seq_along(map.values)){
    AR2 <- arima.sim(n = m, model = list(ar = rho.true))
    fft <- fft(AR2)
    per <- Re(fft)^2 + Im(fft)^2
    lW <- function(rho1, rho2) m*log(sum(ginv(w.vec, rho1, rho2)*per)/m) + sum(log(1/g(w.vec, rho1, rho2)))
    rho.est <- optim(rho.init, lW)
    #With a simulation of total size of m we would be done here excluding the map & for lines.
    rhcollect(1, rho.est)
  }
})
reduce <- expression(
  pre <- {x <- 0}
  reduce <- {x <- x + app}y(unlist(reduce.values), 2, mean)}
  post <- {rhcollect(1, x)}
  )
mr <- rhwatch(
  map      = map,
  reduce   = reduce,
  input    = c(N/m, 10),
  output   = "/tmp/advsim/rho.est",
  mapred   = list(mapred.reduce.tasks = 1),
  readback = FALSE
  )
```

The reduce expression will further reduce final data storage, as a simple averaging of the parameter estimates over the subsets will provide the best estimate over the entire data set provided our data access constraint due to the Central Limit Theorem (CLT). If data storage restraints did not exist, the R numerical optimization method `optim('initial parameter estimate', function)` over the entire data set is more likely to be the better estimate. However, the mean over all the subsets of the data still abides by a Normal Distribution with mean the actual parameter value(s) and variance scaling down by a multiplicative factor of $r^{-1}, r = \frac{N}{m}$ being the number of subsets. Thus, provided the computational difficulties, RHIPE provides a more than satisfactory solution in thei advanced simulation with different parameters example as well as numerous other cases.

